### ISSUE TITLE
Research Testing Tools

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/elastos-ReactNative-framework#56]
Who: Testers and QA
What: Research and find tools that we can use to test what we develop
Why: So we can set a standard and start testing our code automatically with regression testing

Examples:
 - Jest
 - Mocha JS
 - Appium

**Comment by raghulraj** [comment]
**Tools Explored:**

1. Jest
2. Appium
3. Mocha
4. RNTester (Integration tests)
5. Detox

**Types of Test:**
1. Unit Testing (For Native bridges)
2. Integration Tests using RNTester (only for iOS)
3. End to End tests (for demo apps)

**Unit Testing**
Unit Testing can be done using Jest. But it will be on mock implementations of native bridges.Jest is a JavaScript testing tool, it won't run code that you have written in Objective C/Swift/Java in a native module. It doesn't run on a device and therefore cannot import real bridged modules. You can mock the functionality of a native module so that you can call it from JavaScript.

This approach will not really help testing the native bridge modules

Eg: Mock up module for wallet:

```
import {NativeModules} from 'react-native';
import React from 'react';
import renderer from 'react-test-renderer';

describe('TestProject', () => {
  beforeEach(() => {
    NativeModules.TestModule = { generateMnemonic: jest.fn().mockReturnValue('keyword1', 'keyword2', .. ;keyword12'') }
  });
  test('Verify 12 words Mnemonics are generated', async () => {
        await console.log(NativeModules.TestModule.generateMnemonic());
});
});
```

**Integration Test** for Native bridges using RNTester (only for IOS)

Integration Test basically tests integrated components that require both native and JS components to communicate across the bridge. The two main components are RCTTestRunner and RCTTestModule. RCTTestRunner sets up the ReactNative environment and provides facilities to run the tests as XCTestCases in Xcode. RCTTestModule is exported to JS as NativeModules.TestModule. But in my research, I haven't seen any proper integrations tests for any of the big applications. In general people don't write many integration tests for native bridges and the focus is on testing while consuming it in the application.
More details here: [RNTesterIntegrationTests](https://github.com/facebook/react-native/tree/master/RNTester/RNTesterIntegrationTests)

```
Sample references below, its just a boilerplate code.

//Tests.js

var { TestModule } = ReactNative.NativeModules;

var Tests = React.createClass({
  shouldResolve: false,
  shouldReject: false,
  propTypes: {
    RunSampleCall: React.PropTypes.bool
  },
  getInitialState() {
    return {
      done: false,
    };
  },
  componentDidMount() {
    if(this.props.TestName === "testgenerateMnemonic"){
      Promise.all([this.testgenerateMnemonic()]).then(()=>
      {
        TestModule.markTestPassed(this.shouldResolve);
      });
      return;
    }
  },
  async testgenerateMnemonic(){
    // logic goes here..
  }
  render() : ReactElement<any> {
    return <View />;
  }
});

Tests.displayName = 'Tests';


//Tests.m

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>

#import <RCTTest/RCTTestRunner.h>

#import "RCTAssert.h"

#define RCT_TEST(name)                  \
- (void)test##name                      \
{                                       \
[_runner runTest:_cmd module:@#name]; \
}

@interface ElastosExampleWalletTests : XCTestCase

@end

@implementation ElastosExampleWalletTests
{
  RCTTestRunner *_runner;
}

- (void)setUp
{
  _runner = RCTInitRunnerForApp(@"ios/ElastosExampleWalletTests/Tests", nil);
}

- (void)testgenerateMnemonic
{
  // Test logic goes here..
}
#pragma mark Logic Tests

RCT_TEST(Tests)

@end

```

**End to End Testing.**

Here we see things from a user perspective. Appium is the obvious choice when it comes to E2E automation, but there is an another tool, developed by Wix team called Detox, which is used by Facebook for E2E automation. More companies are moving with detox for their e2e automation for their apps.

More details here: [https://github.com/wix/Detox](Detox)
